# Artificial Neural Network

### Importing the libraries

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Importing the dataset

In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   ...   EstimatedSalary  Exited
0          1    15634602   ...         101348.88       1
1          2    15647311   ...         112542.58       0
2          3    15619304   ...         113931.57       1
3          4    15701354   ...          93826.63       0
4          5    15737888   ...          79084.10       0

[5 rows x 14 columns]

In [5]:
X = dataset.iloc[:, 3:13].values
y = dataset.loc[:, 'Exited'].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

### Encoding categorical data(Country and Gender)

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
#Transform Country to Dummy Variables
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
#Avoid Dummy Trap 
X = X[:, 1:]

In [7]:
X.shape

(10000, 11)

### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### Importing the keras libraries of deep learninig

In [12]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [14]:
classifier = Sequential()

### Adding the input layer and first hidden layer

In [22]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

### Adding Second Hidden Layer

In [23]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

### Adding Output Layer

In [24]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

### Compiling the ANN

In [26]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Fitting the ANN to the Training Set 
third argument it's batch observation, we indicate after how many model, we recount weight

In [27]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - ETA: 0s - loss: 0.6144 - acc: 0.7973- ETA: 1s - loss: 0.6360 - acc: 0.797 - ETA: 1s - loss: 0.6 - 4s 439us/step - loss: 0.6142 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 3s 385us/step - loss: 0.5341 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 424us/step - loss: 0.5120 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 4s 490us/step - loss: 0.5069 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 4s 541us/step - loss: 0.5061 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 4s 440us/step - loss: 0.5060 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 4s 455us/step - loss: 0.5059 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 4s 446us/step - loss: 0.5060 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 4s 512us/step - loss: 0.5059 - acc: 0.7960 0s

8000/8000 [==============================] - 5s 635us/step - loss: 0.5060 - acc: 0.7960
Epoch 79/100
8000/8000 [==============================] - 5s 624us/step - loss: 0.5059 - acc: 0.7960
Epoch 80/100
8000/8000 [==============================] - 3s 436us/step - loss: 0.5059 - acc: 0.7960
Epoch 81/100
8000/8000 [==============================] - 3s 381us/step - loss: 0.5059 - acc: 0.7960
Epoch 82/100
8000/8000 [==============================] - 3s 316us/step - loss: 0.5060 - acc: 0.7960
Epoch 83/100
8000/8000 [==============================] - 3s 315us/step - loss: 0.5060 - acc: 0.7960
Epoch 84/100
8000/8000 [==============================] - 2s 307us/step - loss: 0.5059 - acc: 0.7960
Epoch 85/100
8000/8000 [==============================] - 2s 310us/step - loss: 0.5060 - acc: 0.7960
Epoch 86/100
8000/8000 [==============================] - 4s 460us/step - loss: 0.5059 - acc: 0.7960
Epoch 87/100
8000/8000 [==============================] - 3s 317us/step - loss: 0.5059 - acc: 0.7960
Epo

### Prediction The Test Set Result
If results False customer don't leave bank

In [29]:
y_pred = classifier.predict(X_test)
y_pred =(y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1595,    0],
       [ 405,    0]])

In [33]:
print('Accurracy:', 1595 / 2000, '%')

Accurracy: 0.7975 %
